CREATE TABLE utenti (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    cognome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    indirizzo VARCHAR(100) NOT NULL,
    n_civico VARCHAR(5) NOT NULL,
    citta VARCHAR(100) NOT NULL
);